common:
  containerRegistryURL: odocqd021433acr.azurecr.io
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:odocqd021433sqlserver.database.windows.net,1433;Database=local.final_root_sql_database_name-dev;Uid=SQLUser1;Pwd=SQLPass1;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

ui:
  replicas: 1
  image:
    name: todo-ui
    tag: v1
  ingress:
    host: dev-ui.sharmaji.club
  env:
    REACT_APP_GET_TASKS_API_BASE_URL: "http://get-tasks-api.sharmaji.club"
    REACT_APP_DELETE_TASK_API_BASE_URL: "http://delete-task-api.sharmaji.club"
    REACT_APP_CREATE_TASK_API_BASE_URL: "http://add-task-api.sharmaji.club"

addTask:
  replicas: 2
  image:
    name: todo-add-tasks-api
    tag: v1
  ingress:
    host: add-task-api.sharmaji.club

deleteTask:
  replicas: 1
  image:
    name: todo-delete-tasks-api
    tag: v1
  ingress:
    host: delete-task-api.sharmaji.club

getTask:
  replicas: 2
  image:
    name: todo-get-tasks-api
    tag: v1
  ingress:
    host: get-tasks-api.sharmaji.club