apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-delete-tasks-ingress-{{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.deleteTask.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todo-delete-tasks-svc-{{ .Release.Name }}
                port:
                  number: 80
