apiVersion: v1
kind: Service
metadata:
  name: todo-add-tasks-svc-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: todo-add-tasks-{{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8000
