apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-task-deploy-{{ .Release.Name }}
spec:
  replicas: {{ .Values.getTask.replicas }}
  selector:
    matchLabels:
      app: todo-get-task-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: todo-get-task-{{ .Release.Name }}
    spec:
      containers:
      - name: todo-get-task-container-{{ .Release.Name }}
        image: {{ .Values.common.containerRegistryURL }}/{{ .Values.getTask.image.name }}:{{ .Values.getTask.image.tag }}
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: {{ .Values.common.connectionString }}
          

