apiVersion: v1
kind: Service
metadata:
  name: todo-get-task-svc-{{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: todo-get-task-{{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8000
